module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'orders',
    WISHLIST_COLLECTION:'wishlist',
    ADMIN_COLLECTION:'admin',
    DELIVERY_COLLECTION:'delivery',
    SUPERADMIN_COLLECTION:'superadmin'
}